name: CI

# Controls when the action will run. 
on:
  push:
    # Match all pushes
  pull_request:
    # Match all pull requests
  schedule:
    - cron: "0 6 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    paths-ignore:
    - '.github/**'
    - 'lists/**'
    - '*.txt'
    - '*.yaml'
    - '*.conf'
    - '*.txt'
    - '*.sh'
    - '*.py'
    - '*.json'
    - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 'Convert Lists'
        run: python ./convertlists.py lists.json /converted/
      - name: 'Build Repo'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "AGH"
          git push
